# Generated by Django 4.1.7 on 2023-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsmodel',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN_ROLE_TYPE'), ('ARTIST', 'ARTIST_ROLE_TYPE'), ('ORGANIZATION', 'ORGANIZATION_ROLE_TYPE'), ('USER', 'USER_ROLE_TYPE')], help_text='Type of role.', max_length=15),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN_ROLE_TYPE'), ('ARTIST', 'ARTIST_ROLE_TYPE'), ('ORGANIZATION', 'ORGANIZATION_ROLE_TYPE'), ('USER', 'USER_ROLE_TYPE')], help_text='Type of role.', max_length=15),
        ),
    ]
