# Generated by Django 4.1.7 on 2023-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_alter_permissionsmodel_role_alter_userlogininfo_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogininfo',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userlogininfo',
            name='parent',
        ),
        migrations.AddField(
            model_name='userlogininfo',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userlogininfo',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userlogininfo',
            name='profile_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='auth_type',
            field=models.CharField(choices=[('EMAIL', 'EMAIL_LOGIN_TYPE'), ('PHONE', 'PHONE_LOGIN_TYPE'), ('GOOGLE', 'GOOGLE_LOGIN_TYPE'), ('LINKEDIN', 'LINKEDIN_LOGIN_TYPE'), ('FACEBOOK', 'FACEBOOK_LOGIN_TYPE')], default='EMAIL', help_text='Type of authentication.', max_length=15),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN_ROLE_TYPE'), ('ARTIST', 'ARTIST_ROLE_TYPE'), ('ORGANIZATION', 'ORGANIZATION_ROLE_TYPE'), ('USER', 'USER_ROLE_TYPE')], default='USER', help_text='Type of role.', max_length=15),
        ),
    ]
