# Generated by Django 4.1.7 on 2023-03-18 16:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_remove_userlogininfo_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('logo', models.URLField(blank=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('address', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('country', models.CharField(blank=True, default='', max_length=30)),
                ('pin', models.CharField(blank=True, default='', max_length=30)),
                ('working_since', models.DateTimeField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artist_Info',
                'verbose_name_plural': 'Artist Information',
                'db_table': 'artist_model',
            },
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organizationmodel',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='organizationmodel',
            name='establish_date',
        ),
        migrations.RemoveField(
            model_name='organizationmodel',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='organizationmodel',
            name='theme',
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='StoreModel',
        ),
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
