# Generated by Django 4.1.7 on 2023-03-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_artistmodel_remove_userprofilemodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogininfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
