# Generated by Django 4.1.7 on 2023-03-18 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_alter_userlogininfo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Category_Info',
                'verbose_name_plural': 'Category Information',
                'db_table': 'category_model',
            },
        ),
        migrations.RemoveField(
            model_name='artistmodel',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='artistmodel',
            name='pin',
        ),
        migrations.AddField(
            model_name='artistmodel',
            name='fees',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='artistmodel',
            name='fees_category',
            field=models.CharField(choices=[('EVENT', 'EVENT'), ('DAY', 'DAY'), ('HOUR', 'HOUR'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR')], default='EVENT', max_length=10),
        ),
        migrations.AddField(
            model_name='artistmodel',
            name='fees_currency',
            field=models.CharField(choices=[('RS', 'RUPEE_CURRENCY'), ('PHONE', 'DOLLOR_CURRENCY')], default='RS', max_length=10),
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='commission_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artistmodel',
            name='category',
            field=models.ManyToManyField(to='myapps.categorymodel'),
        ),
    ]
