# Generated by Django 4.1.7 on 2023-03-18 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0006_categorymodel_remove_artistmodel_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi-NCR', 'Delhi-NCR'), ('Bengaluru', 'Bengaluru'), ('Ahmedabad', 'Ahmedabad'), ('Chandigarh', 'Chandigarh'), ('Chennai', 'Chennai'), ('Pune', 'Pune'), ('Kolkata', 'Kolkata'), ('Kochi', 'Kochi')], max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=30)),
                ('working_since', models.DateTimeField(blank=True)),
                ('fees', models.PositiveIntegerField(default=0, null=True)),
                ('fees_currency', models.CharField(choices=[('RS', 'RUPEE_CURRENCY'), ('PHONE', 'DOLLOR_CURRENCY')], default='RS', max_length=10)),
                ('category', models.ManyToManyField(to='myapps.categorymodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event_Info',
                'verbose_name_plural': 'Event Information',
                'db_table': 'event_model',
            },
        ),
    ]
