# Generated by Django 4.1.7 on 2023-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0007_eventmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='user',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='artistmodel',
            name='fees_category',
        ),
        migrations.RemoveField(
            model_name='artistmodel',
            name='fees_currency',
        ),
        migrations.RemoveField(
            model_name='organizationmodel',
            name='commission_percentage',
        ),
        migrations.RemoveField(
            model_name='organizationmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organizationmodel',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='userlogininfo',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='artists',
            field=models.ManyToManyField(to='myapps.artistmodel'),
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='regular_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='sale_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
