# Generated by Django 4.1.7 on 2023-03-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0010_remove_eventmodel_working_since'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistmodel',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='artistmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organizationmodel',
            name='logo',
        ),
    ]
