# Generated by Django 4.1.7 on 2023-03-18 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0013_alter_eventmodel_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 20, 53, 55, 956558, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='regular_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='sale_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
