# Generated by Django 4.1.7 on 2023-03-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0014_eventmodel_event_date_eventmodel_regular_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='fees',
        ),
    ]
