# Generated by Django 4.1.7 on 2023-03-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0017_eventmodel_meeting_password_eventmodel_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='meeting_password',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
