# Generated by Django 4.1.7 on 2023-03-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0018_alter_eventmodel_meeting_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
