# Generated by Django 4.1.7 on 2023-03-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0020_eventmodel_grid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh')], max_length=30),
        ),
    ]
