# Generated by Django 4.1.7 on 2023-03-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0021_alter_eventmodel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogininfo',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='userlogininfo',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userlogininfo',
            name='social_id',
        ),
        migrations.DeleteModel(
            name='PermissionsModel',
        ),
    ]
