# Generated by Django 4.1.7 on 2023-03-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0023_alter_eventmodel_options_eventregistrationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistrationModel',
        ),
    ]
