# Generated by Django 4.1.7 on 2023-03-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0025_eventregistrationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguageModel',
        ),
        migrations.DeleteModel(
            name='UserLocationModel',
        ),
    ]
