# Generated by Django 4.1.7 on 2023-03-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0026_delete_languagemodel_delete_userlocationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='booking_count',
            field=models.IntegerField(default=0),
        ),
    ]
