# Role Type
SUPER_ADMIN_ROLE_TYPE = 'SUPER_ADMIN'
ORGANIZATION_ROLE_TYPE = 'ORGANIZATION'
USER_ROLE_TYPE = 'USER'
ARTIST_ROLE_TYPE = 'ARTIST'
ROLE_TYPE = (
    (SUPER_ADMIN_ROLE_TYPE, 'SUPER_ADMIN_ROLE_TYPE'),
    (ARTIST_ROLE_TYPE, 'ARTIST_ROLE_TYPE'),
    (ORGANIZATION_ROLE_TYPE, 'ORGANIZATION_ROLE_TYPE'),
    (USER_ROLE_TYPE, 'USER_ROLE_TYPE')
)
ROLE_TYPE_LIST = [SUPER_ADMIN_ROLE_TYPE, ORGANIZATION_ROLE_TYPE, USER_ROLE_TYPE, ARTIST_ROLE_TYPE]
DEFAULT_ROLE_TYPE = USER_ROLE_TYPE

CITIES = (
    ("Mumbai", 'Mumbai'),
    ("Delhi", 'Delhi'),
    ("Chandigarh", 'Chandigarh')
)
